# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fbbc2b7337281b4cf29bf8c3ccfb640c369a7e7e3ed4d4986a096fd600404b0700c4855c8c4f6b6a48bc19e98867b05396609a0a102e36c7d98aa234653a2d1

test:
  secret_key_base: 7dfc2e91acc8144e4f4bc74b64666e85e611e9cdf3912c7fe4d3bb9dd3bc845232a8ee932686d22aa01232f262ee9bb0c581b2cc11d9a1158fe3b5f876a0e567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
